[project]
name = "lazybear"
version = "0.1.0"
description = "Polars-like lazy access to a database."
requires-python = ">=3.10"
dependencies = [
    "polars>=1.36.1",
    "pyarrow>=22.0.0",
    "sqlalchemy>=2.0.45",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
pythonpath = 'src'

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
